Proxy_filename          = x509up
Proxy_path              = /afs/cern.ch/user/a/apiccine/private/$(Proxy_filename)
universe                = vanilla
x509userproxy           = $(Proxy_path)
use_x509userproxy       = true
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_input_files    = $(Proxy_path), samples/samples.py, skimtree_utils_ssWW_wFakes.py, CutsAndValues_bu.py, FR_vsjet2_vsmuT.root, FR_vsjet4_vsmuT.root, ./data/leptonSF/Muon_RunBCDEF_SF_ID_2017.root, TauIDSFTool.py, EFTOperator_dict.py, __init__.py, ./data
transfer_output_remaps  = "TTZToLLNuNu_2017_part15.root=/eos/home-a/apiccine/VBS/nosynch/v80/ltau/TTZToLLNuNu_2017/TTZToLLNuNu_2017_part15.root"
+JobFlavour             = "testmatch"
executable              = tree_skimmer_ssWW_wFakes.py
arguments               = TTZToLLNuNu_2017 15 root://cms-xrd-global.cern.ch//store/user/apiccine/VBS/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8/TTZToLLNuNu_2017/210420_100957/0000/tree_hadd_15.root remote VT VL T
output                  = condor_v80/ltau/output/TTZToLLNuNu_2017_VTVLT_part15.out
error                   = condor_v80/ltau/error/TTZToLLNuNu_2017_VTVLT_part15.err
log                     = condor_v80/ltau/log/TTZToLLNuNu_2017_VTVLT_part15.log
queue
