Proxy_filename          = x509up
Proxy_path              = /afs/cern.ch/user/m/mmagheri/private/$(Proxy_filename)
universe                = vanilla
x509userproxy           = $(Proxy_path)
use_x509userproxy       = true
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_input_files    = $(Proxy_path), samples/samples.py, FakeRatio_utils_dev.py, CutsAndValues_bu.py, __init__.py
transfer_output_remaps  = "GluGluToContinToZZTo4tau_2017_part18.root=/eos/home-m/mmagheri/VBS/nosynch/Fake_v40/vsJet4/GluGluToContinToZZTo4tau_2017/GluGluToContinToZZTo4tau_2017_part18.root"
+JobFlavour             = "workday"
executable              = FakeRatio_dev.py
arguments               = GluGluToContinToZZTo4tau_2017 18 root://cms-xrd-global.cern.ch//store/user/apiccine/VBSFake/GluGluToContinToZZTo4tau_13TeV_MCFM701_pythia8/GluGluToContinToZZTo4tau_2017_FakeHT/210625_120126/0000/tree_hadd_19.root remote HT 4
output                  = condor_FRTau4/output/GluGluToContinToZZTo4tau_2017_part18.out
error                   = condor_FRTau4/error/GluGluToContinToZZTo4tau_2017_part18.err
log                     = condor_FRTau4/log/GluGluToContinToZZTo4tau_2017_part18.log
queue
